---------- normal exceptions --------------------
throw new Exception():                        OK
java.lang.Exception
   at extest.main (extest.java:21)

throw new Exception() (from subroutines):     OK
java.lang.Exception
   at extest.sub4 (extest.java:422)
   at extest.sub3 (extest.java:418)
   at extest.sub2 (extest.java:414)
   at extest.sub (extest.java:410)
   at extest.main (extest.java:36)

NullPointerException:                         OK
java.lang.NullPointerException
   at extest.main (extest.java:46)


---------- test soft inline exceptions ----------
/* thrown twice to check the inline jump code */
ArithmeticException (only w/ -softnull):      OK
java.lang.ArithmeticException: / by zero
   at extest.main (extest.java:61)

ArithmeticException (only w/ -softnull):      OK
java.lang.ArithmeticException: / by zero
   at extest.main (extest.java:77)

ArrayIndexOutOfBoundsException:               OK
java.lang.ArrayIndexOutOfBoundsException: -889275714
   at extest.main (extest.java:95)

ArrayIndexOutOfBoundsException:               OK
java.lang.ArrayIndexOutOfBoundsException: -1161901314
   at extest.main (extest.java:112)

ArrayStoreException:                          OK
java.lang.ArrayStoreException
   at extest.main (extest.java:132)

ArrayStoreException:                          OK
java.lang.ArrayStoreException
   at extest.main (extest.java:143)

ClassCastException:                           OK
java.lang.ClassCastException
   at extest.main (extest.java:154)

ClassCastException:                           OK
java.lang.ClassCastException
   at extest.main (extest.java:165)

NegativeArraySizeException (newarray):        OK
java.lang.NegativeArraySizeException
   at extest.main (extest.java:175)

NegativeArraySizeException (newarray):        OK
java.lang.NegativeArraySizeException
   at extest.main (extest.java:184)

NegativeArraySizeException (multianewarray):  OK
java.lang.NegativeArraySizeException
   at extest.main (extest.java:193)

NullPointerException (only w/ -softnull):     OK
java.lang.NullPointerException
   at extest.main (extest.java:204)

NullPointerException (only w/ -softnull):     OK
java.lang.NullPointerException
   at extest.main (extest.java:214)

OutOfMemoryError:                             OK
java.lang.OutOfMemoryError
   at extest.main (extest.java:224)

OutOfMemoryError:                             OK
java.lang.OutOfMemoryError
   at extest.main (extest.java:234)

OutOfMemoryError (multianewarray):            OK
java.lang.OutOfMemoryError
   at extest.main (extest.java:244)


---------- exceptions in leaf functions ---------
ArithmeticException:                          OK
java.lang.ArithmeticException: / by zero
   at extest.aesub (extest.java:426)
   at extest.main (extest.java:258)

ArrayIndexOutOfBoundsException:               OK
java.lang.ArrayIndexOutOfBoundsException: -559038737
   at extest.aioobesub (extest.java:430)
   at extest.main (extest.java:267)

ClassCastException:                           OK
java.lang.ClassCastException
   at extest.ccesub (extest.java:434)
   at extest.main (extest.java:284)

NullPointerException:                         OK
java.lang.NullPointerException
   at extest.npesub (extest.java:438)
   at extest.main (extest.java:293)


---------- some asmpart exceptions --------------
NullPointerException in <clinit> (PUTSTATIC): OK
java.lang.ExceptionInInitializerError
   at extest.main (extest.java:307)
Caused by: java.lang.NullPointerException
   at extest_clinit_1.<clinit> (extest.java:477)
   at extest.main (extest.java:307)

NullPointerException in <clinit> (GETSTATIC): OK
java.lang.ExceptionInInitializerError
   at extest.main (extest.java:320)
Caused by: java.lang.NullPointerException
   at extest_clinit_2.<clinit> (extest.java:486)
   at extest.main (extest.java:320)


---------- exception related things -------------
load/link an exception class in asmpart:      OK
java.lang.Exception
   at extest.main (extest.java:338)


---------- native stub exceptions ---------------
NullPointerException in <clinit>:             OK
java.lang.ExceptionInInitializerError
   at extest.main (extest.java:355)
Caused by: java.lang.NullPointerException
   at extest_clinit_3.<clinit> (extest.java:495)
   at extest.main (extest.java:355)

UnsatisfiedLinkError:                         OK
java.lang.UnsatisfiedLinkError: nsub
   at extest.nsub (Native Method)
   at extest.main (extest.java:367)

NullPointerException (native):                OK
java.lang.NullPointerException
   at java.lang.VMSystem.arraycopy (Native Method)
   at java.lang.System.arraycopy (System.java:234)
   at extest.main (extest.java:376)


---------- special exceptions -------------------
OutOfMemoryError (array clone):               OK
java.lang.OutOfMemoryError
   at [B.clone (Native Method)
   at extest.main (extest.java:391)


---------- no OK beyond this point --------------
NullPointerException (without catch):
Exception in thread "main" java.lang.NullPointerException
   at extest.main (extest.java:405)
